name: Deploy Quartz site to GitHub Pages
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/checkout@master
        with:
          repository: juanca37/${{ secrets.OBSIDIAN_REPO }}
          ref: main
          token: ${{ secrets.PAT }}
          path: ${{ secrets.OBSIDIAN_REPO }}
      - name: Debugging 
        run: ls ${{ secrets.OBSIDIAN_REPO }}
      - name: Copying blog content into folder
        run: |
          cp ${{ secrets.OBSIDIAN_REPO }}/${{ secrets.OBSIDIAN_BLOG_FOLDER }}/. content -r
      - name: Debugging 
        run: ls content
      - name: Removing OBSIDIAN_REPO
        run: rm -rf ${{ secrets.OBSIDIAN_REPO }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4